routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['prefix' => 'quan-tri','middleware' => 'auth'], function() {

    Route::get('/', 'HomeController@index')->name('admin');
    //menu
    Route::get('/menu','Admin\MenuController@menurender')->name('menu');
    // user
    Route::resource('user','Admin\UserController');
    // role
    Route::resource('roles', 'Admin\RoleController');
    //Page
    Route::resource('page', 'Admin\PageController');
    Route::resource('postcate', 'Admin\PostCategoryController');
    Route::resource('post', 'Admin\PostController');
    Route::resource('page', 'Admin\PageController');
    Route::resource('productcate', 'Admin\ProductCategoryController');
    Route::resource('product', 'Admin\ProductController');
    Route::post('uploadImg', 'Admin\ImageController@postImages')->name('adminimg'); 
    Route::post('deleteImg', 'Admin\ImageController@delImages')->name('adminimgdel'); 
    //File manager
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});
Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

resources/views/admin/page/create.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                    <div class="m-portlet m-portlet--mobile">
                            <div class="m-portlet__head">
                                  <div class="m-portlet__head-caption">
                                        <div class="m-portlet__head-title">
                                              <h3 class="m-portlet__head-text">
                                                   Tạo Trang Tĩnh
                                              </h3>
                                        </div>
                                  </div>
                                  <div class="m-portlet__head-tools">
                                        <ul class="m-portlet__nav">
                                              <li class="m-portlet__nav-item">
                                                                    </li>
                                        </ul>
                                  </div>
                                  
                            </div>
                            <div class="m-portlet__body">
                                    @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong>Lỗi<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" role="form" method="POST" action="{{ route('page.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-12 control-label">Tên trang</label>

                                <div class="col-md-12">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" onkeyup="ChangeToSlug()"
                                           required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                              <label for="thumbnail" class="col-md-5 control-label">Thumbnail</label>
                                <span class="form-group-btn">
                                  <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary text-white">
                                    <i class="fa fa-picture-o"></i> Chọn
                                  </a>
                                </span>
                                <input id="thumbnail" class="form-control" type="text" name="thumbnail" value="">
                              </div>
                              <img id="holder" style="margin-top:15px;max-height:100px;" src="">

                            <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                                <label for="slug" class="col-md-12 control-label">Slug trang</label>

                                <div class="col-md-12">
                                    <input id="slug" type="text" class="form-control" name="slug" value="{{ old('slug') }}"
                                           >

                                    @if ($errors->has('slug'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                          <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                              <label for="email" class="col-md-12 control-label">Mô tả ngắn</label>

                              <div class="col-md-12">
                                            <textarea id="description" name="description" class="form-control my-editor"></textarea>
                                  @if ($errors->has('description'))
                                      <span class="help-block">
                                      <strong>{{ $errors->first('description') }}</strong>
                                  </span>
                                  @endif
                              </div>
                          </div>

                            <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                                <label for="body" class="col-md-12 control-label">Nội Dung</label>

                                <div class="col-md-12">
                                              <textarea id="body" name="body" class="form-control my-editor" rows="40"></textarea>
                                    @if ($errors->has('body'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('body') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>




                            <div class="form-group">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary">
                                        Tạo mới
                                    </button>

                                    <a class="btn btn-link" href="{{ route('page.index') }}">
                                        Hủy
                                    </a>
                                </div>
                            </div>
                        </form>
                            </div>
                      </div>
            </div>
        </div>

        <script src="{{ asset('/vendor/laravel-filemanager/js/lfm.js')}}"></script>

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">
$('#lfm').filemanager('image');
function ChangeToSlug()
        {
            var title, slug;

            //Lấy text từ thẻ input title
            title = document.getElementById("title").value;

            //Đổi chữ hoa thành chữ thường
            slug = title.toLowerCase();

            //Đổi ký tự có dấu thành không dấu
            slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
            slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
            slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
            slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
            slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
            slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
            slug = slug.replace(/đ/gi, 'd');
            //Xóa các ký tự đặt biệt
            slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
            //Đổi khoảng trắng thành ký tự gạch ngang
            slug = slug.replace(/ /gi, "-");
            //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
            //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
            slug = slug.replace(/\-\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-/gi, '-');
            slug = slug.replace(/\-\-/gi, '-');
            //Xóa các ký tự gạch ngang ở đầu và cuối
            slug = '@' + slug + '@';
            slug = slug.replace(/\@\-|\-\@|\@/gi, '');
            //In slug ra textbox có id “slug”
            // var url = '{{ url('/page/')}}';
            // document.getElementById('link').value = url +'/'+ slug;
            document.getElementById('slug').value = slug;

        }
var editor_config = {
path_absolute : "/",
selector: "textarea.my-editor",
plugins: [
  "advlist autolink lists link image charmap print preview hr anchor pagebreak",
  "searchreplace wordcount visualblocks visualchars code fullscreen",
  "insertdatetime media nonbreaking save table contextmenu directionality",
  "emoticons template paste textcolor colorpicker textpattern"
],
toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
relative_urls: false,
file_browser_callback : function(field_name, url, type, win) {
  var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
  var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

  var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
  if (type == 'image') {
    cmsURL = cmsURL + "&type=Images";
  } else {
    cmsURL = cmsURL + "&type=Files";
  }

  tinyMCE.activeEditor.windowManager.open({
    file : cmsURL,
    title : 'Filemanager',
    width : x * 0.8,
    height : y * 0.8,
    resizable : "yes",
    close_previous : "no"
  });
}
};

tinymce.init(editor_config);


</script>
    </div>


@endsection

resources/views/admin/page/edit.blade.php
<?php ?>

@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
            <div class="m-portlet m-portlet--mobile">
                    <div class="m-portlet__head">
                          <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                      <h3 class="m-portlet__head-text">
                                            Bài Viết
                                      </h3>
                                </div>
                          </div>
                          <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                      <li class="m-portlet__nav-item">
                                                            </li>
                                </ul>
                          </div>
                          
                    </div>
                    <div class="m-portlet__body">
                            <div class="m-portlet__head-tools">
                                    @if (count($errors) > 0)
                                   <div class="alert alert-danger">
                                       <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                       <ul>
                                           @foreach ($errors->all() as $error)
                                               <li>{{ $error }}</li>
                                           @endforeach
                                       </ul>
                                   </div>
                               @endif
       
       
                               <form class="form-horizontal" role="form" method="POST"
                                     action="{{ route('page.update',$data2->id) }}">
                                   {{ csrf_field() }}
                                   {{ method_field('PATCH') }}
       
                                   <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                       <label for="title" class="col-md-12 control-label">Tên Trang</label>
       
                                       <div class="col-md-12">
                                           <input id="title" type="text" class="form-control" name="title" value="{{ $data2->title }}" onkeyup="ChangeToSlug()"
                                                  required autofocus>
       
                                           @if ($errors->has('title'))
                                               <span class="help-block">
                                               <strong>{{ $errors->first('title') }}</strong>
                                           </span>
                                           @endif
                                       </div>
                                   </div>
       
                                   <div class="form-group col-md-12">
                                     <label for="thumbnail" class="col-md-5 control-label">Thumbnail</label>
                                       <span class="form-group-btn">
                                         <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary text-white">
                                           <i class="fa fa-picture-o"></i> Chọn
                                         </a>
                                       </span>
                                       <input id="thumbnail" class="form-control col-md-12" type="text" name="thumbnail" value="{{$data2->thumbnail}}">
                                         <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ asset($data2->thumbnail)}}">
                                     </div>
       
       
                                   <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                                       <label for="slug" class="col-md-12 control-label">Slug trang</label>
       
                                       <div class="col-md-12">
                                           <input id="slug" type="text" class="form-control" name="slug" value="{{ $data2->slugs->slug }}"
                                                  >
       
                                           @if ($errors->has('slug'))
                                               <span class="help-block">
                                               <strong>{{ $errors->first('slug') }}</strong>
                                           </span>
                                           @endif
                                       </div>
                                   </div>
                                   <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                       <label for="email" class="col-md-12 control-label">Mô tả ngắn</label>
       
                                       <div class="col-md-12">
                                                     <textarea id="description" name="description" class="form-control my-editor">{{$data2->description}}</textarea>
                                           @if ($errors->has('description'))
                                               <span class="help-block">
                                               <strong>{{ $errors->first('description') }}</strong>
                                           </span>
                                           @endif
                                       </div>
                                   </div>
       
                                   <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                                       <label for="email" class="col-md-12 control-label">Nội Dung </label>
       
                                       <div class="col-md-12">
                                                     <textarea id="description" name="body" rows="40" class="form-control my-editor">{{$data2->body}}</textarea>
                                           @if ($errors->has('body'))
                                               <span class="help-block">
                                               <strong>{{ $errors->first('body') }}</strong>
                                           </span>
                                           @endif
                                       </div>
                                   </div>
       
       
       
                                   <div class="form-group">
                                       <div class="col-md-8 col-md-offset-4">
                                           <button type="submit" class="btn btn-primary">
                                               Sửa
                                           </button>
       
                                           <a class="btn btn-link" href="{{ route('page.index') }}">
                                               Hủy
                                           </a>
                                       </div>
                                   </div>
                               </form>
                         
                    </div>
              </div>

        </div>
        <script src="{{ asset('/vendor/laravel-filemanager/js/lfm.js')}}"></script>

        <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
        <script type="text/javascript">
        $('#lfm').filemanager('image');
        function ChangeToSlug()
                {
                    var title, slug;
        
                    //Lấy text từ thẻ input title
                    title = document.getElementById("title").value;
        
                    //Đổi chữ hoa thành chữ thường
                    slug = title.toLowerCase();
        
                    //Đổi ký tự có dấu thành không dấu
                    slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
                    slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
                    slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
                    slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
                    slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
                    slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
                    slug = slug.replace(/đ/gi, 'd');
                    //Xóa các ký tự đặt biệt
                    slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
                    //Đổi khoảng trắng thành ký tự gạch ngang
                    slug = slug.replace(/ /gi, "-");
                    //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
                    //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
                    slug = slug.replace(/\-\-\-\-\-/gi, '-');
                    slug = slug.replace(/\-\-\-\-/gi, '-');
                    slug = slug.replace(/\-\-\-/gi, '-');
                    slug = slug.replace(/\-\-/gi, '-');
                    //Xóa các ký tự gạch ngang ở đầu và cuối
                    slug = '@' + slug + '@';
                    slug = slug.replace(/\@\-|\-\@|\@/gi, '');
                    //In slug ra textbox có id “slug”
                    // var url = '{{ url('/page/')}}';
                    // document.getElementById('link').value = url +'/'+ slug;
                    document.getElementById('slug').value = slug;
        
                }
        var editor_config = {
        path_absolute : "/",
        selector: "textarea.my-editor",
        plugins: [
          "advlist autolink lists link image charmap print preview hr anchor pagebreak",
          "searchreplace wordcount visualblocks visualchars code fullscreen",
          "insertdatetime media nonbreaking save table contextmenu directionality",
          "emoticons template paste textcolor colorpicker textpattern"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
        relative_urls: false,
        file_browser_callback : function(field_name, url, type, win) {
          var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
          var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
        
          var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
          if (type == 'image') {
            cmsURL = cmsURL + "&type=Images";
          } else {
            cmsURL = cmsURL + "&type=Files";
          }
        
          tinyMCE.activeEditor.windowManager.open({
            file : cmsURL,
            title : 'Filemanager',
            width : x * 0.8,
            height : y * 0.8,
            resizable : "yes",
            close_previous : "no"
          });
        }
        };
        
        tinymce.init(editor_config);
        
        
        </script>
    </div>


@endsection

resources/views/admin/page/index.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
      <div class="col-md-12">
                  @if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                      <button type="button" class="close" data-dismiss="alert"></button>	
                          <strong>{{ $message }}</strong>
                  </div>
                  @endif
      </div>
        <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                      <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                  <h3 class="m-portlet__head-text">
                                        Trang Tĩnh
                                  </h3>
                            </div>
                      </div>
                      <div class="m-portlet__head-tools">
                            <ul class="m-portlet__nav">
                                  <li class="m-portlet__nav-item">
                                                        </li>
                            </ul>
                      </div>
                      
                </div>
                <div class="m-portlet__body">

                      <!--begin: Search Form -->
                      <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                            <div class="row align-items-center">
                                  <div class="col-xl-8 order-2 order-xl-1">
                                        
                                  </div>
                                  <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                  <a href="{{ route('page.create') }}" class="btn btn-info m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                              <span>
                                                    <i class="la la-cart-plus"></i>
                                                    <span>Tạo Mới Trang Tĩnh</span>
                                              </span>
                                        </a>					
                                        <div class="m-separator m-separator--dashed d-xl-none"></div>					
                                  </div>
                            </div>
                      </div>
                      <!--end: Search Form -->
          
                      <!--begin: Datatable -->
                      <div class="m_datatable" id="child_data_ajax">

                                  <table class="data-table m-datatable__table">
                                              <thead>
                                                  <tr>
                                                      <th>No</th>
                                                      <th>Tên Trang</th>
                                                      <th width="100px">Action</th>
                                                  </tr>
                                              </thead>
                                              <tbody>
                                              </tbody>
                                          </table>
                      </div>
                      <!--end: Datatable -->
                </div>
          </div>

    @routes

<script type="text/javascript">
$(document).ready(function(){
  $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
});
var table = $('.data-table').DataTable({
    processing: true,
    serverSide: true,
    ajax: "{{ route('page.index') }}",
    columns: [
        {data: 'DT_RowIndex', name: 'DT_RowIndex'},
        {data: 'title', name: 'title'},
        {data: 'action', name: 'action', orderable: false, searchable: false},
    ]
});

$('body').on('click', '.deleteUser', function () {
  //$(".deleteUser").click(function(){
 
 var page_id = $(this).data("id");
 var r = confirm("Bạn chắc chắn muốn xóa !");
 if (r == true) {
    $.ajax({
     type: "POST",
     data: {_method: 'delete'},
     url: route('page.destroy',{id: page_id}),
     success: function (data) {
         table.draw();
     },
     error: function (data) {
         console.log('Error:', data);
     }
 });
} else {
  return false;
}
 
});
$(".alert").fadeTo(2000, 500).slideUp(500, function(){
    $(".alert").slideUp(500);
});

});
</script>
</div>
@endsection

resources/views/admin/page/show.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Chi tiết trang</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="title" class="col-md-4 control-label">Tên trang</label>
                            {{ $data->title }}
                        </div>


                        <div class="form-group">
                            <label for="description" class="col-md-4 control-label">Mô tả trang</label>
                            {{ $data->description }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection