routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(['prefix' => 'quan-tri','middleware' => 'auth'], function() {

    Route::get('/', 'HomeController@index')->name('admin');
    //menu
    Route::get('/menu','Admin\MenuController@menurender')->name('menu');
    // user
    Route::resource('user','Admin\UserController');
    // role
    Route::resource('roles', 'Admin\RoleController');
    //Page
    Route::resource('page', 'Admin\PageController');
    Route::resource('postcate', 'Admin\PostCategoryController');
    Route::resource('post', 'Admin\PostController');
    Route::resource('page', 'Admin\PageController');
    Route::resource('productcate', 'Admin\ProductCategoryController');
    Route::resource('product', 'Admin\ProductController');
    Route::post('uploadImg', 'Admin\ImageController@postImages')->name('adminimg'); 
    Route::post('deleteImg', 'Admin\ImageController@delImages')->name('adminimgdel'); 
    //File manager
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
});
Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

resources/views/admin/productcate/create.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
            <div class="m-portlet m-portlet--mobile">
                    <div class="m-portlet__head">
                          <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                      <h3 class="m-portlet__head-text">
                                            Tạo mới danh mục
                                      </h3>
                                </div>
                          </div>
                          <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                      <li class="m-portlet__nav-item">
                                                            </li>
                                </ul>
                          </div>
                          
                    </div>
                    <div class="m-portlet__body">
    
                          <!-- Display Validation Errors -->
                        @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form class="form-horizontal" role="form" method="POST" action="{{ route('productcate.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{$errors->has('title') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-12 control-label">Tên danh mục</label>

                            <div class="col-md-12">
                                <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" onkeyup="ChangeToSlug()"
                                       required autofocus>

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                            <label for="slug" class="col-md-12 control-label">Slug danh mục</label>

                            <div class="col-md-12">
                                <input id="slug" type="text" class="form-control" name="slug" value="{{ old('slug') }}"
                                       >

                                @if ($errors->has('slug'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('slug') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group col-md-12">
                          <label for="">Danh mục cha</label>
                          <select name="parent_id" class="form-control">
                              <option value="0">Chọn</option>
                              <?php categoryParent($datas); ?>

                          </select>
                      </div>


                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-12 control-label">Mô tả</label>

                            <div class="col-md-12">
                                <input id="description" type="text" class="form-control" name="description" value="{{ old('description') }}"
                                       required autofocus>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>




                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Tạo mới
                                </button>

                                <a class="btn btn-link" href="{{ route('productcate.index') }}">
                                    Hủy
                                </a>
                            </div>
                        </div>
                    </form>

                    </div>
              </div>
    </div>

    <!-- <script src="{{ asset('/vendor/laravel-filemanager/js/lfm.js')}}"></script> -->

 <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">

    function ChangeToSlug()
            {
                var title, slug;

                //Lấy text từ thẻ input title
                title = document.getElementById("title").value;

                //Đổi chữ hoa thành chữ thường
                slug = title.toLowerCase();

                //Đổi ký tự có dấu thành không dấu
                slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
                slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
                slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
                slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
                slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
                slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
                slug = slug.replace(/đ/gi, 'd');
                //Xóa các ký tự đặt biệt
                slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
                //Đổi khoảng trắng thành ký tự gạch ngang
                slug = slug.replace(/ /gi, "-");
                //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
                //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
                slug = slug.replace(/\-\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-/gi, '-');
                slug = slug.replace(/\-\-/gi, '-');
                //Xóa các ký tự gạch ngang ở đầu và cuối
                slug = '@' + slug + '@';
                slug = slug.replace(/\@\-|\-\@|\@/gi, '');
                //In slug ra textbox có id “slug”
                // var url = '{{ url('/page/')}}';
                // document.getElementById('link').value = url +'/'+ slug;
                document.getElementById('slug').value = slug;

            }
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endsection

resources/views/admin/productcate/edit.blade.php
<?php ?>

@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
            <div class="m-portlet m-portlet--mobile">
                    <div class="m-portlet__head">
                          <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                      <h3 class="m-portlet__head-text">
                                           Sửa Danh Mục
                                      </h3>
                                </div>
                          </div>
                          <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                      <li class="m-portlet__nav-item">
                                                            </li>
                                </ul>
                          </div>
                          
                    </div>
                    <div class="m-portlet__body">
    
                        <!-- Display Validation Errors -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        <form class="form-horizontal" role="form" method="POST"
                              action="{{ route('productcate.update',$data->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-12 control-label">Tên danh mục</label>

                                <div class="col-md-12">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ $data->title }}" onkeyup="ChangeToSlug()"
                                    >

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                                <label for="slug" class="col-md-4 control-label">Slug danh mục</label>

                                <div class="col-md-12">
                                    <input id="slug" type="text" class="form-control" name="slug" value="{{ $data->slugs->slug }}"
                                           >

                                    @if ($errors->has('slug'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group col-md-12">
                              <label for="">Danh mục cha</label>
                              <select name="parent_id" class="form-control">
                                  <option value="0">Chọn</option>
                                  <?php categoryParent($datas,0,"",$data->parent_id); ?>

                              </select>
                          </div>
                          
                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="mota" class="col-md-12 control-label">Mô tả</label>

                                <div class="col-md-12">
                                    <input id="description" type="text" class="form-control" name="description" value="{{ $data->description }}"
                                           required autofocus>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Sửa
                                    </button>

                                    <a class="btn btn-link" href="{{ route('productcate.index') }}">
                                        Hủy
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
              </div>

    </div>

    <!-- <script src="{{ asset('/vendor/laravel-filemanager/js/lfm.js')}}"></script> -->

 <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">

    function ChangeToSlug()
            {
                var title, slug;
    
                //Lấy text từ thẻ input title
                title = document.getElementById("title").value;
    
                //Đổi chữ hoa thành chữ thường
                slug = title.toLowerCase();
    
                //Đổi ký tự có dấu thành không dấu
                slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
                slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
                slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
                slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
                slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
                slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
                slug = slug.replace(/đ/gi, 'd');
                //Xóa các ký tự đặt biệt
                slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
                //Đổi khoảng trắng thành ký tự gạch ngang
                slug = slug.replace(/ /gi, "-");
                //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
                //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
                slug = slug.replace(/\-\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-\-/gi, '-');
                slug = slug.replace(/\-\-\-/gi, '-');
                slug = slug.replace(/\-\-/gi, '-');
                //Xóa các ký tự gạch ngang ở đầu và cuối
                slug = '@' + slug + '@';
                slug = slug.replace(/\@\-|\-\@|\@/gi, '');
                //In slug ra textbox có id “slug”
                // var url = '{{ url('/page/')}}';
                // document.getElementById('link').value = url +'/'+ slug;
                document.getElementById('slug').value = slug;
    
            }
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endsection

resources/views/admin/productcate/index.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
      <div class="col-md-12">
                  @if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                      <button type="button" class="close" data-dismiss="alert"></button>	
                          <strong>{{ $message }}</strong>
                  </div>
                  @endif
      </div>
        <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                      <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                  <h3 class="m-portlet__head-text">
                                        Danh Mục
                                  </h3>
                            </div>
                      </div>
                      <div class="m-portlet__head-tools">
                            <ul class="m-portlet__nav">
                                  <li class="m-portlet__nav-item">
                                                        </li>
                            </ul>
                      </div>
                      
                </div>
                <div class="m-portlet__body">

                      <!--begin: Search Form -->
                      <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                            <div class="row align-items-center">
                                  <div class="col-xl-8 order-2 order-xl-1">
                                        
                                  </div>
                                  <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                  <a href="{{ route('productcate.create') }}" class="btn btn-info m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                              <span>
                                                    <i class="la la-cart-plus"></i>
                                                    <span>Tạo Mới Danh Mục</span>
                                              </span>
                                        </a>					
                                        <div class="m-separator m-separator--dashed d-xl-none"></div>					
                                  </div>
                            </div>
                      </div>
                      <!--end: Search Form -->
          
                      <!--begin: Datatable -->
                      <div class="m_datatable" id="child_data_ajax">

                                  <table class="data-table m-datatable__table">
                                              <thead>
                                                  <tr>
                                                      <th>No</th>
                                                      <th>Tên Danh Mục</th>
                                                      <th>Tên Danh Mục Cha</th>
                                                      <th width="100px">Action</th>
                                                  </tr>
                                              </thead>
                                              <tbody>
                                              </tbody>
                                          </table>
                      </div>
                      <!--end: Datatable -->
                </div>
          </div>

    @routes

<script type="text/javascript">
$(document).ready(function(){
  $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
});
var table = $('.data-table').DataTable({
    processing: true,
    serverSide: true,
    ajax: "{{ route('productcate.index') }}",
    columns: [
        {data: 'DT_RowIndex', name: 'DT_RowIndex'},
        {data: 'title', name: 'title'},
        {data: 'parent', name: 'parent'},
        {data: 'action', name: 'action', orderable: false, searchable: false},
    ]
});

$('body').on('click', '.deleteUser', function () {
  //$(".deleteUser").click(function(){
 
 var page_id = $(this).data("id");
 var r = confirm("Bạn chắc chắn muốn xóa !");
 if (r == true) {
    $.ajax({
     type: "POST",
     data: {_method: 'delete'},
     url: route('productcate.destroy',{id: page_id}),
     success: function (data) {
         table.draw();
     },
     error: function (data) {
         console.log('Error:', data);
     }
 });
} else {
  return false;
}
 
});
$(".alert").fadeTo(2000, 500).slideUp(500, function(){
    $(".alert").slideUp(500);
});

});
</script>
</div>
@endsection

resources/views/admin/productcate/show.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Chi tiết danh mục</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="title" class="col-md-4 control-label">Tên danh mục</label>
                            {{ $data->title }}
                        </div>


                        <div class="form-group">
                            <label for="description" class="col-md-4 control-label">Mô tả danh mục</label>
                            {{ $data->description }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection